rules:
  color-hex-case: "lower"
#  color-hex-length: null
#  color-named: null
#  color-no-hex: null
  color-no-invalid-hex: true

#  font-family-name-quotes: null
  font-family-no-duplicate-names: true

  "font-weight-notation": "named-where-possible"

  function-blacklist: []
#  function-calc-no-unspaced-operator: null
  function-comma-newline-after: "never-multi-line"
  function-comma-newline-before: "never-multi-line"
#  function-comma-space-after: null # IT disabled because there are many bugs
  function-comma-space-before: "never"
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: "lower"
  function-parentheses-newline-inside: "never-multi-line"
  function-parentheses-space-inside: "never"
  #function-url-data-uris: "never" // DEPRECATED
#  function-url-scheme-blacklist: null
#  function-url-no-scheme-relative: null
  function-url-quotes: "always"
  function-url-scheme-whitelist: ["https", "data"]
#  function-whitelist: null # TODO: add correct list of function
  function-whitespace-after: "always"

  number-leading-zero: "always"
  number-max-precision: 5
  number-no-trailing-zeros: true

  string-no-newline: true
  string-quotes: "single"

  length-zero-no-unit: true

  time-min-milliseconds: 50

  unit-blacklist: [] # TODO: add correct list of units
  unit-case: "lower"
#  unit-no-unknown: null # disabled for support LESS syntax

#  value-keyword-case: null # disabled for support LESS syntax
  value-no-vendor-prefix: true
  value-list-comma-newline-after: "always-multi-line"
  value-list-comma-newline-before: "never-multi-line"
#  value-list-comma-space-after: null
#  value-list-comma-space-before: null
  value-list-max-empty-lines: 0

  custom-property-empty-line-before: "always"
#  custom-property-pattern: null

  property-blacklist: [] # TODO: add correct list of properties
  property-case: "lower"
  property-no-unknown: true
  property-no-vendor-prefix: true
#  property-whitelist: null # TODO: add correct list of properties

  keyframe-declaration-no-important: true

  declaration-bang-space-after: "never"
  declaration-bang-space-before: "always"
#  declaration-colon-newline-after: null
  declaration-colon-space-after: "always"
  declaration-colon-space-before: "never"
#  declaration-empty-line-before: null
  declaration-no-important: true
#  declaration-property-unit-blacklist: null # TODO: add correct list of declarations
#  declaration-property-unit-whitelist: null
#  declaration-property-value-blacklist: null # TODO: add correct list of declaration-values
#  declaration-property-value-whitelist: null
  declaration-block-no-duplicate-properties: true
#  declaration-block-no-ignored-properties: null
#  declaration-block-no-redundant-longhand-properties: null # TODO: enable it!
#  declaration-block-no-shorthand-property-overrides: null # TODO: enable it!
#  declaration-block-properties-order: null
  declaration-block-semicolon-newline-after: "always"
  declaration-block-semicolon-newline-before: "never-multi-line"
  declaration-block-semicolon-space-after: "always-single-line"
  declaration-block-semicolon-space-before: "never"
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: "always"

  block-closing-brace-empty-line-before: "never"
  block-closing-brace-newline-after: "always"
  block-closing-brace-newline-before: "always-multi-line"
#  block-closing-brace-space-after: null # TODO: enable it!
  block-closing-brace-space-before: "always-single-line"
#  block-no-empty: null
#  block-no-single-line: null
  block-opening-brace-newline-after: "always-multi-line"
#  block-opening-brace-newline-before: null # TODO: enable it!
  block-opening-brace-space-after: "always-single-line"
  block-opening-brace-space-before: "always"

  selector-attribute-brackets-space-inside: "never"
  selector-attribute-operator-blacklist: [] # TODO: add correct list of operators
  selector-attribute-operator-space-after: "never"
  selector-attribute-operator-space-before: "never"
#  selector-attribute-operator-whitelist: null
  selector-attribute-quotes: "always"
  selector-class-pattern: "^([A-Z][a-zA-Z0-9]+)(__[a-z][a-zA-Z0-9]*)?(--(gen-)?[a-z][a-zA-Z0-9]*)?$"
  selector-combinator-space-after: "always"
  selector-combinator-space-before: "always"
  selector-descendant-combinator-no-non-space: true
#  selector-id-pattern: null # TODO: enable it!
#  selector-max-compound-selectors: null # TODO: enable it!
#  selector-max-specificity: null # TODO: enable it!
#  selector-nested-pattern: null # TODO: enable it!
  selector-max-attribute: 0
#  selector-no-combinator: null
  selector-max-id: 0
#  selector-no-qualifying-type: null # TODO: enable it!
#  selector-no-type: null # TODO: enable it!
  selector-max-universal: 0
#  selector-no-vendor-prefix: null # TODO: enable it!
  selector-pseudo-class-blacklist: [] # TODO: add correct list of pseudo-classes
#  selector-pseudo-class-case: null # doesn't fit to us
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: "never"
#  selector-pseudo-class-whitelist: null
  selector-pseudo-element-case: "lower"
  selector-pseudo-element-colon-notation: "double"
  selector-pseudo-element-no-unknown: true
  selector-type-case: "lower"
  selector-type-no-unknown: true
  selector-max-empty-lines: 3
  selector-list-comma-newline-after: "always"
  selector-list-comma-newline-before: "never-multi-line"
  selector-list-comma-space-after: "always-single-line"
  selector-list-comma-space-before: "never"
#  rule-empty-line-before: null
#  rule-non-nested-empty-line-before: null

  media-feature-colon-space-after: "always"
  media-feature-colon-space-before: "never"
#  media-feature-name-blacklist: null # TODO: add correct list of feature-names
  media-feature-name-case: "lower"
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
#  media-feature-name-whitelist: null
  media-feature-parentheses-space-inside: "never"
  media-feature-range-operator-space-after: "always"
  media-feature-range-operator-space-before: "always"
#  custom-media-pattern: null
  media-query-list-comma-newline-after: "never-multi-line"
  media-query-list-comma-newline-before: "never-multi-line"
  media-query-list-comma-space-after: "always"
  media-query-list-comma-space-before: "never"
#  at-rule-blacklist: null # TODO: add correct list of rules
#  at-rule-empty-line-before: null
  at-rule-name-case: "lower"
#  at-rule-name-newline-after: null
#  at-rule-name-space-after: null
#  at-rule-no-unknown: null
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: "always"
  at-rule-semicolon-space-before: "never"
#  at-rule-whitelist: null
#  stylelint-disable-reason: null
#  comment-empty-line-before: null
#  comment-no-empty: null
#  comment-whitespace-inside: null
#  comment-word-blacklist: null
  indentation: 2
  max-empty-lines: 3
#  max-line-length: null
#  max-nesting-depth: null
#  no-descending-specificity: null
  no-duplicate-selectors: true
#  no-empty-source: null
  no-eol-whitespace: true
  no-extra-semicolons: true
#  no-invalid-double-slash-comments: null
  no-missing-end-of-source-newline: true
  no-unknown-animations: true

  # to be continued
